Feature: Story
cleverpush/cleverpush-ios-sdk pull request #18
Opened 2021-06-18 14:51 UTC by Azharhussain20

Feature: Story and Story details.

2021-07-02 23:06 UTC, gbhrdt requested changes

2021-07-05 07:21 UTC, Azharhussain20 commented on CleverPush/CleverPush/Source/CPTranslate.m
> +                @"emptyString": @"Please enter storyid",
Ok I will remove those strings from CPTranslate.m and will you please suggest me the exact error message what it could be?

2021-07-05 20:35 UTC, gbhrdt commented on CleverPush/CleverPush/Source/CPTranslate.m
> +                @"emptyString": @"Please enter storyid",
Please enter a valid story ID.

2021-07-05 20:51 UTC, gbhrdt commented
Please also change:
- Rename CPWidget* files/classes to CPStoryWidget*
- Rename `widgetStoryId` parameter of StoryView to `storyWidgetId`
- Rename family to fontFamily
- When I switch between 2 stories there is a small space. Remove this space:
![image](https://user-images.githubusercontent.com/1145196/124516877-fa806d00-dde2-11eb-93df-71e4bbafa840.png)
- When a new story is loading do *not*  show the webview content before the story is ready. Otherwise it shows some white page with blue text:
- Clicking links on the stories (Buttons / Swipe ups) does not work. It should open a SafariViewController (behaviour like the appBanners with openInWebview)
- When I reach the last page of the last story, it should not go back to Story 1 again, instead it should close
- The story bubbles should have some active effect when I press my finger on them before releasing it (for example a bit less opacity)

Already fixed by my commit:
- CPStoryView.h, CPStory.h, CPStoryContent.h, CPStoryContentMeta.h, CPStoryContentPreview.h, CPWidgetVariant.h, CPWidgetPosition.h, CPWidgetDisplay.h, CPStoryWidget.h, UIImageView+CleverPush need to be Public Members of CleverPushFramework Target
- CPWKWebView.h/.m need to be Project Members of CleverPushFramework Target

2021-07-15 14:27 UTC, gbhrdt commented
@Azharhussain20 please resolve merge conflicts

2021-07-15 14:27 UTC, gbhrdt requested changes
@Azharhussain20 please resolve merge conflicts

2021-08-04 15:33 UTC, merged