feature/CP-4533-version-comparison-code
cleverpush/cleverpush-ios-sdk pull request #86
Opened 2022-09-28 11:33 UTC by cpandya25

CP-4533 App version comparator class added with comparison.

2022-10-04 22:11 UTC, gbhrdt requested changes

2022-10-04 22:11 UTC, gbhrdt commented on CleverPush/CleverPush/Source/CPAppBannerModuleInstance.m
> +        if (allowed && [value isEqualToVersion:compareValue] == TRUE) {
YES

2022-10-04 22:11 UTC, gbhrdt commented on CleverPush/CleverPush/Source/CPAppBannerModuleInstance.m
> +        if ([value isEqualOrOlderThanVersion:compareValue] == TRUE) {
YES

2022-10-04 22:11 UTC, gbhrdt commented on CleverPush/CleverPush/Source/CPAppBannerModuleInstance.m
> +        if ([value isEqualOrNewerThanVersion:compareValue] == TRUE) {
YES

2022-10-05 10:14 UTC, gbhrdt requested changes

2022-10-05 10:14 UTC, gbhrdt commented on CleverPush/Source/CPAppVersionComparator.m
> +- (NSComparisonResult) CompareToVersion:(NSString *)version {
`- (NSComparisonResult)compareToVersion:(NSString *)version {`

2022-10-05 10:14 UTC, gbhrdt commented on CleverPush/Source/CPAppVersionComparator.h
> +- (NSComparisonResult)CompareToVersion:(NSString *)version;
`- (NSComparisonResult)compareToVersion:(NSString *)version {`

2022-10-05 10:14 UTC, gbhrdt commented on CleverPush/Source/CPAppBannerModuleInstance.m
> +#import "CPAppVersionComparator.h"
Add new line after

2022-10-05 10:14 UTC, gbhrdt commented on CleverPush/Source/CPAppBannerModuleInstance.m
> +        if ([value isEqualOrNewerThanVersion:compareValue] == YES) {
Actually we don't need `== YES` We can just do
`if ([value isEqualOrNewerThanVersion:compareValue]) {`

Also apply to all other conditions please.

Same with NO, just check if `!condition`

2022-10-05 11:43 UTC, cpKevinrodriguesnobre requested changes

2022-10-05 11:43 UTC, cpKevinrodriguesnobre commented on CleverPush/Source/CPAppVersionComparator.m
> +    return ([self compareToVersion:version] == NSOrderedAscending);
() not necessary here and below

2022-10-05 11:43 UTC, cpKevinrodriguesnobre commented on CleverPush/Source/CPAppVersionComparator.m
> +    return ([self compareToVersion:version] == NSOrderedDescending);
()

2022-10-05 11:43 UTC, cpKevinrodriguesnobre commented on CleverPush/Source/CPAppVersionComparator.m
> +    return ([self compareToVersion:version] == NSOrderedSame);
()

2022-10-05 11:43 UTC, cpKevinrodriguesnobre commented on CleverPush/Source/CPAppVersionComparator.m
> +    return ([self compareToVersion:version] != NSOrderedDescending);
()

2022-10-05 11:43 UTC, cpKevinrodriguesnobre commented on CleverPush/Source/CPAppVersionComparator.m
> +    return ([self compareToVersion:version] != NSOrderedAscending);
()

2022-10-05 11:43 UTC, cpKevinrodriguesnobre commented on CleverPush/Source/CPAppVersionComparator.m
> +    if ([self isEqualToString:version])
always use {} here
if(){
}

2022-10-05 12:51 UTC, cpKevinrodriguesnobre approved these changes

2022-10-05 12:54 UTC, merged